"""Initial migration: users, sessions, generated_readmes tables

Revision ID: bc8712053550
Revises: 8697b711b9ff
Create Date: 2026-01-19 04:17:24.272522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc8712053550'
down_revision: Union[str, None] = '8697b711b9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_table('generated_readmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=True),
    sa.Column('input_method', sa.Enum('PUBLIC_URL', 'FILE_UPLOAD', 'GITHUB_AUTH', name='inputmethod'), nullable=False),
    sa.Column('readme_content', sa.Text(), nullable=False),
    sa.Column('was_committed', sa.Boolean(), nullable=False),
    sa.Column('was_downloaded', sa.Boolean(), nullable=False),
    sa.Column('commit_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_readmes_id'), 'generated_readmes', ['id'], unique=False)
    op.create_index(op.f('ix_generated_readmes_session_id'), 'generated_readmes', ['session_id'], unique=False)
    op.create_index(op.f('ix_generated_readmes_user_id'), 'generated_readmes', ['user_id'], unique=False)
    op.add_column('users', sa.Column('github_username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'github_token',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_users_github_username'), 'users', ['github_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_username'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'github_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'github_username')
    op.drop_index(op.f('ix_generated_readmes_user_id'), table_name='generated_readmes')
    op.drop_index(op.f('ix_generated_readmes_session_id'), table_name='generated_readmes')
    op.drop_index(op.f('ix_generated_readmes_id'), table_name='generated_readmes')
    op.drop_table('generated_readmes')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
