"""Add branch to generated_readmes

Revision ID: bf2f5b33222f
Revises: a2c1f635a96e
Create Date: 2026-02-07 18:39:09.334992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2f5b33222f'
down_revision: Union[str, None] = 'a2c1f635a96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_readmes', sa.Column('branch', sa.String(), nullable=True))
    op.execute("UPDATE generated_readmes SET branch = 'main' WHERE branch IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_readmes', 'branch')

    # ### end Alembic commands ###
