import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import {
  Loader2,
  GitPullRequest,
  GitBranch,
  FileText,
  Info,
  ArrowLeft,
  Check,
} from "lucide-react";
import { getReadme, commitReadme } from "../services/api";
import CommitSuccessModal from "../components/CommitSuccessModal";
import toast from "react-hot-toast";
export default function CommitPage() {
  const navigate = useNavigate();
  const location = useLocation();

  // State for readme data
  const [readmeId, setReadmeId] = useState(null);
  const [readmeData, setReadmeData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Parsed repository info for file tile
  const [repoOwner, setRepoOwner] = useState("");
  const [repoName, setRepoName] = useState("");

  // Form state
  const [commitMessage, setCommitMessage] = useState("");
  const [extendedDescription, setExtendedDescription] = useState("");

  // Commit state
  const [isCommitting, setIsCommitting] = useState(false);
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [commitResult, setCommitResult] = useState(null);
  useEffect(() => {
    const loadReadmeData = async () => {
      try {
        // 1. Get readmeId from location state or URL query params
        const navState = location.state;
        let id = navState?.readmeId;

        if (!id) {
          const params = new URLSearchParams(location.search);
          id = params.get("id");
        }

        if (!id) {
          const savedId = sessionStorage.getItem("commitReadmeId");
          if (savedId) id = savedId;
        }

        if (!id) {
          toast.error("No README ID provided");
          navigate("/");
          return;
        }

        sessionStorage.setItem("commitReadmeId", id);
        setReadmeId(id);
        // 2. Fetch README data from API
        const data = await getReadme(id);

        // 3. Check if input_method is github_auth
        const inputMethod = data.input_method || "";
        const isGitHubAuth = inputMethod.toLowerCase() === "github_auth";

        // 4. If not github_auth: redirect to home page
        if (!isGitHubAuth) {
          toast.error("Only GitHub OAuth READMEs can be committed directly.");
          navigate("/");
          return;
        }

        // 5. Parse owner/repo from repo_url
        if (data.repo_url) {
          const url = data.repo_url.replace(/\/$/, "");
          const parts = url.split("/");
          if (parts.length >= 2) {
            setRepoOwner(parts[parts.length - 2] || "");
            setRepoName(parts[parts.length - 1] || "");
          }
        }

        setReadmeData(data);
      } catch (err) {
        console.error("Error loading README:", err);
        setError(err.message || "Failed to load README data");
        toast.error("Failed to load README data");
      } finally {
        setLoading(false);
      }
    };
    loadReadmeData();
  }, [location, navigate]);

  // Pre-fill form with default values
  useEffect(() => {
    setCommitMessage("Add comprehensive README.md via DocRelief AI");
    setExtendedDescription(`Generated by DocRelief AI
• Added project overview and features
• Included installation and usage instructions
• Added contribution guidelines`);
  }, []);

  // Handle commit submission
  const handleCommit = async () => {
    setIsCommitting(true);

    try {
      // Get user ID from localStorage
      const userData = localStorage.getItem("github_user");
      let userId = null;

      if (userData) {
        try {
          const parsed = JSON.parse(userData);
          userId = parsed.id;
        } catch (e) {
          console.error("Error parsing user data:", e);
        }
      }

      if (!userId) {
        toast.error("Please authenticate with GitHub first");
        navigate("/");
        return;
      }

      // Trim the commit message and extended description
      const trimmedMessage = commitMessage.trim();
      const trimmedDescription = extendedDescription.trim() || null;

      // Make the commit request
      const result = await commitReadme(
        userId,
        readmeId,
        trimmedMessage,
        trimmedDescription,
      );

      // Store result and show success modal
      setCommitResult(result);
      setShowSuccessModal(true);
    } catch (err) {
      console.error("Commit error:", err);

      // Check if it's a network error
      if (
        !err.response &&
        err.message &&
        err.message.includes("Network Error")
      ) {
        toast.error(
          "Network error. Please check your connection and try again.",
        );
      } else {
        // API error - show the error detail from response
        const errorMessage =
          err.response?.data?.detail ||
          err.message ||
          "Failed to commit README";
        toast.error(errorMessage);
      }
    } finally {
      setIsCommitting(false);
    }
  };

  // Loading state
  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center page-gradient">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="w-10 h-10 animate-spin text-green-400" />
          <p className="text-gray-400 font-medium">Loading commit details...</p>
        </div>
      </div>
    );
  }

  // Error state
  if (error || !readmeData) {
    return (
      <div className="min-h-screen page-gradient flex items-center justify-center p-4">
        <div className="text-center max-w-md bg-[#1C2B3A]/60 backdrop-blur-md border border-green-500/40 shadow-[0_0_20px_rgba(34,197,94,0.15)] rounded-2xl p-8">
          <div className="mb-6">
            <GitPullRequest className="mx-auto h-16 w-16 text-red-400" />
          </div>
          <h1 className="text-3xl font-bold text-gray-100 mb-4">
            README Not Found
          </h1>
          <p className="text-gray-400 mb-8">
            {error || "The README doesn't exist."}
          </p>
          <button
            onClick={() => navigate("/")}
            className="px-6 py-3 bg-green-500 hover:bg-green-400 text-black font-medium rounded-lg transition-colors"
          >
            Go Back Home
          </button>
        </div>
      </div>
    );
  }

  return (
    <>
      <div className="min-h-screen page-gradient py-8 px-4">
        <div className="max-w-2xl mx-auto bg-[#1C2B3A]/60 backdrop-blur-md border border-green-500/40 shadow-[0_0_20px_rgba(34,197,94,0.15)] rounded-2xl p-8">
          {/* Header Section */}
          <div className="mb-8">
            <div className="flex items-center gap-3">
              <span className="w-6 h-6 text-green-400">
                <GitBranch className="w-6 h-6" />
              </span>
              <h1 className="text-2xl font-bold text-gray-100">
                Commit Details
              </h1>
            </div>
          </div>

          {/* Form Section */}
          <div className="mb-6 space-y-6">
            {/* Commit Message Field */}
            <div className="space-y-2">
              <label
                htmlFor="commitMessage"
                className="block text-lg font-semibold text-gray-200"
              >
                Commit Message
              </label>
              <p className="text-gray-500 text-sm">
                Describe what this commit does
              </p>
              <input
                type="text"
                id="commitMessage"
                value={commitMessage}
                onChange={(e) => setCommitMessage(e.target.value)}
                maxLength={200}
                disabled={isCommitting}
                placeholder="Add comprehensive README.md via DocRelief AI"
                className="w-full px-4 py-3 bg-[#1C2B3A]/60 border border-green-500/40 text-gray-200 placeholder-gray-500 rounded-xl focus:outline-none focus:border-green-400 focus:shadow-[0_0_15px_rgba(34,197,94,0.15)] transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              />
              <p
                className={`text-sm mt-2 text-right ${commitMessage.length > 180 ? "text-orange-400 font-medium" : "text-gray-500"}`}
              >
                {commitMessage.length}/200 characters
              </p>
            </div>

            {/* Extended Description Field */}
            <div className="space-y-2">
              <label
                htmlFor="extendedDescription"
                className="block text-lg font-semibold text-gray-200"
              >
                Extended Description (Optional)
              </label>
              <p className="text-gray-500 text-sm">
                Add more context about this commit
              </p>
              <textarea
                id="extendedDescription"
                value={extendedDescription}
                onChange={(e) => setExtendedDescription(e.target.value)}
                rows={6}
                disabled={isCommitting}
                placeholder="Generated by DocRelief AI"
                className="w-full px-4 py-3 bg-[#1C2B3A]/60 border border-green-500/40 text-gray-200 placeholder-gray-500 rounded-xl focus:outline-none focus:border-green-400 focus:shadow-[0_0_15px_rgba(34,197,94,0.15)] transition-all resize-none disabled:opacity-50 disabled:cursor-not-allowed"
              />
            </div>
          </div>

          {/* Target Branch Section */}
          <div className="mb-6">
            <h2 className="text-lg font-semibold text-gray-200 mb-2">
              Target Branch
            </h2>
            <p className="text-gray-500 text-sm mb-3">
              README.md will be committed in branch:
            </p>
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-[#1C2B3A]/60 border border-green-500/40 rounded-lg">
              <span className="w-2.5 h-2.5 rounded-full bg-green-400" />
              <GitBranch className="w-4 h-4 text-green-400" />
              <span className="text-gray-200 font-medium">
                {readmeData?.branch || "main"}
              </span>
            </div>
          </div>

          {/* Changes Section */}
          <div className="mb-8 border border-green-500/40 rounded-xl p-6">
            <h3 className="text-lg font-semibold text-gray-200 mb-4">
              Changes to be committed:
            </h3>

            {/* File tile */}
            <div className="bg-green-500/10 border border-green-500/40 rounded-lg p-4 mb-4 flex items-center gap-3">
              <FileText className="w-5 h-5 text-green-400" />
              <div className="flex flex-col">
                <span className="font-semibold text-gray-200">README.md</span>
                <span className="text-sm text-gray-500">
                  {repoOwner}/{repoName}
                </span>
              </div>
            </div>

            {/* Info message box */}
            <div className="bg-blue-500/10 border border-blue-500/40 rounded-lg p-4 flex items-start gap-3">
              <Info className="w-5 h-5 text-blue-400 flex-shrink-0 mt-0.5" />
              <p className="text-sm text-blue-300 leading-relaxed">
                This will create a new README.md file in the root of your
                repository. If a README already exists, it will be updated.
              </p>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center justify-between gap-4">
            <button
              onClick={() => navigate(-1)}
              className="flex items-center gap-2 px-6 py-3 bg-white/10 hover:bg-white/20 text-gray-200 border border-white/10 rounded-lg font-medium transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Preview
            </button>

            <button
              onClick={handleCommit}
              disabled={
                !commitMessage.trim() ||
                commitMessage.length > 200 ||
                isCommitting
              }
              className="flex items-center gap-2 px-6 py-3 bg-green-500 hover:bg-green-400 disabled:opacity-50 disabled:cursor-not-allowed text-black font-medium rounded-lg transition-colors"
            >
              {isCommitting ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Committing...
                </>
              ) : (
                <>
                  <Check className="w-4 h-4" />
                  Commit to GitHub
                </>
              )}
            </button>
          </div>
        </div>

        {/* Success Modal */}
        <CommitSuccessModal
          isOpen={showSuccessModal}
          onClose={() => setShowSuccessModal(false)}
          commitData={commitResult}
          readmeId={readmeId}
        />
      </div>
    </>
  );
}
